### ISSUE TITLE
A Javascript error occurred

### ISSUE THREAD

**Issue by ddechant** [aza547/wow-recorder#134]
I get the follow error after running the application while in a raid instance. Logging was already enabled.

![image](https://user-images.githubusercontent.com/263218/191399700-163742d8-c6cf-4e6a-a075-1f39ecca460b.png)

**Comment by tdaugaard** [comment]
Would you happen to have the combat log that caused this and would you be willing to share it either here or in a DM on Discord so I can replay it and see if I can reproduce the error?

**Comment by ddechant** [comment]
Sent you the combat logs in discord.

**Comment by tdaugaard** [comment]
Ah, I see! Thanks a lot - a player died before the raid encounter started and because of that, it was trying to access a timestamp of then the video started recording, but that hadn't been set yet - only set when something starts.

The fix is of course to only handle unit deaths when something is in progress.

**Comment by aza547** [comment]
Fixed in next release.
