### ISSUE TITLE
Crash on game close

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#239]
**Describe the bug**
Exiting WoW raises the following error dialogue

![Screenshot-2022-12-07-040349-WarcraftRecorder](https://user-images.githubusercontent.com/82328511/206069967-30cada02-5a34-46c6-86a8-b05fd2108ac9.png)

**Comment by Squimbert** [comment]
i am also having the same issue

**Comment by idubs** [comment]
I'm experiencing the same issue.

**Comment by aza547** [comment]
I can't reproduce this on my PC. Can you provide logs / repro steps please?

**Comment by aza547** [comment]
Assuming this is on latest version (3.1.0)?

**Comment by idubs** [comment]
Using the latest version.

Steps to reproduce
1. Open World of Warcraft
2. Log in to a character
3. Close World of Warcraft
The error will occur in a few seconds, could probably just close WoW right away too.

[WarcraftRecorder-2022-12-07.log](https://github.com/aza547/wow-recorder/files/10180980/WarcraftRecorder-2022-12-07.log)

I am using OBS because the automatic selection was a black screen.

**Comment by aza547** [comment]
cheers - I'll investigate shortly

**Comment by aza547** [comment]
Seems this happens when a retail path is configured but a classic path is not - hence why I couldn't reproduce it. 

Fix coming in next release. Thanks for the reports. https://github.com/aza547/wow-recorder/commit/48a5d20e50a4192826ab72f76b01e9c2fd43a74d
