### ISSUE TITLE
Raid capture stops "too early"

### ISSUE THREAD

**Issue by JH0Ni-github** [aza547/wow-recorder#49]
Would be nice to have it continue for about 10-30 seconds for achievement pop-ups and guild kill reactions :P SimpleCombatLogger already has the option to "Delay the stopping of combat logging by 30 seconds, this can help compatibility with some external programs".

**Comment by aza547** [comment]
Agreed! I've been working on implementing a recording buffer to correctly capture encounters/arena games from the start. That's also included adding an "over run" value to the end of videos so the score screen shows up. 

I've just added some config so that raid encounter recording will continue 10s after the ENCOUNTER_END event is fired. Coming in the next release (expected to be 2.5.0). Potential future task to make the length of this time configurable.

**Comment by aza547** [comment]
2.5.0 is released so going to mark this as fixed, if you feel the fix isn't good enough please re-open!
