### ISSUE TITLE
21:9 resolution missing, custom resolution support?

### ISSUE THREAD

**Issue by vaisest** [aza547/wow-recorder#526]
**Is your feature request related to a problem? Please describe.**
Title explains it. The closest resolution I'm offered is 3440x1440 (21.5:9), which isn't the same as WoW's 3360x1440 so the video has a black bar on it

**Describe the solution you'd like**
Being able to type it in manually like in OBS would be nice

**Comment by aza547** [comment]
Hello, thanks for submitting an issue. I have never heard of a monitor being 3360x1440, are you not playing WoW on full screen or so? Adding the resolution is trivial, I can do that. Probably not going to redesign the UI to take a custom resolution because it allows users to do stupid things (different encoders have resolution rules, etc.)

**Comment by aza547** [comment]
I've added the resolution in https://github.com/aza547/wow-recorder/commit/5171e34e1f407d301a16c6c158eb340e64cfec99. It will be available in the new release. Please feel free to re-open if you have further thoughts.
