### ISSUE TITLE
Options to record for other types of dungeons (timewalking, heroic, normal)

### ISSUE THREAD

**Issue by divineblade7** [aza547/wow-recorder#563]
I know this is geared towards mythic+ but would love to be able to have a setting to record my normal dungeons runs automattically when leveling. And just timewalking dungeons when farming those. 

If combat logging doesnt have an event to show normal, heroic, TW dungeons starts, maybe it could be integrated with this that starts logging on specified dungeons automatically? https://www.curseforge.com/wow/addons/loggerhead
https://github.com/dratr/loggerhead

I understand its not what everyone would want, so just a toggle option or anything would be so great. this is wonderful, thank you!

**Comment by aza547** [comment]
A few people have asked for this before. This is hard because there are no events for normal dungeons in the same way there are for mythic+. Mythic+ has the CHALLENGE_MODE_[START/STOP] events which we can use to trigger recording. Sadly not feasible to do anything here unless blizzard implement more detailed combat log events for normal dungeons.

**Comment by divineblade7** [comment]
With the reference to loggerhead, would that work for those that want to do it? Since it is starting and stopping the logging in those dungeons automatically? Or just having the logs for that wouldn’t be enough cause of the missing start and stop events?

**Comment by aza547** [comment]
It is possible to react to ZONE_CHANGE events which do exist. That's how WCR handles battlegrounds currently. But I sort of regret ever adding battlegrounds support. It's just too hard work. There are too many caveats for it to be a robust feature.
